---
- hosts: all
  gather_facts: false
  tasks:
  - name: Pre-Setup
    include_role:
      name: pre_setup
- hosts: host
  gather_facts: false
  tasks:
  - name: Host tasks
    include_role:
      name: host
- hosts: client
  gather_facts: false
  tasks:
  - name: Client tasks
    include_role:
      name: client
